# Generated by Django 2.2.10 on 2020-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('url_to_image', models.TextField()),
                ('published_at', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
